apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: self-healing-api
  namespace: default
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: self-healing-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: self-healing-api
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: self-healing-api-1.0.0
    isMainInterface: "yes"
    tier: self
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: self-healing-api
      app.kubernetes.io/name: self-healing-api
      isMainInterface: "yes"
      tier: self
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: self-healing-api
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: self-healing-api
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: self-healing-api-1.0.0
        isMainInterface: "yes"
        tier: self
    spec:
      imagePullSecrets: []
      securityContext: {}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: api
          securityContext: {}
          image: eclipseaerios/self-healing-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8500
            hostPort: 8500
            protocol: TCP
          resources: {}
